/**
 * ARTICLE SLUG REGISTRY (V102)
 * Maps V5 Filenames to V4 URL Slugs.
 * RESTORED: Absolute Case-Sensitivity matching V5 internal linking.
 */

export const ARTICLE_MAP = [
  // CASE-SENSITIVE FILENAMES (V5)
  { file: "AIInGameDev", slug: "AIInGameDev" },
  { file: "APIDeprecationTracker", slug: "APIDeprecationTracker" },
  { file: "AdNetworkIntegrations", slug: "AdNetworkIntegrations" },
  { file: "BeginnerDeployment", slug: "BeginnerDeployment" },
  { file: "BuildErrorPatternTracking", slug: "BuildErrorPatternTracking" },
  { file: "BuildTroubleshooting", slug: "BuildTroubleshooting" },
  { file: "CICDWebGL", slug: "CICDWebGL" },
  { file: "CloudStreamingBrowserTech", slug: "CloudStreamingBrowserTech" },
  { file: "ContentModerationAgeRatings", slug: "ContentModerationAgeRatings" },
  { file: "DeprecatedAPICalls", slug: "DeprecatedAPICalls" },
  { file: "DeveloperForumSignals", slug: "DeveloperForumSignals" },
  { file: "DiscordActivitiesAPISplit", slug: "DiscordActivitiesAPISplit" },
  { file: "EUDMAArticle7", slug: "EUDMAArticle7" },
  { file: "GDPRCCPACompliance", slug: "GDPRCCPACompliance" },
  { file: "GameInvestingGuide", slug: "GameInvestingGuide" },
  { file: "GameValuationsMA", slug: "GameValuationsMA" },
  { file: "GodotAlternativeEngines", slug: "GodotAlternativeEngines" },
  { file: "HyperCasualMarket", slug: "HyperCasualMarket" },
  { file: "IAPStarsTON", slug: "IAPStarsTON" },
  { file: "IPLicensingWebGL", slug: "IPLicensingWebGL" },
  { file: "InvestorDueDiligenceGuide", slug: "InvestorDueDiligenceGuide" },
  { file: "LinkedInB2BGaming", slug: "LinkedInB2BGaming" },
  { file: "MetaSDKMigration", slug: "MetaSDKMigration" },
  { file: "PIIPrivacyCompliance", slug: "PIIPrivacyCompliance" },
  { file: "PerformanceProfiling", slug: "PerformanceProfiling" },
  { file: "PlatformAPIChangeAlerts", slug: "PlatformAPIChangeAlerts" },
  { file: "RegulatoryBulletins", slug: "RegulatoryBulletins" },
  { file: "SDKIntegrationGuides", slug: "SDKIntegrationGuides" },
  { file: "September30Sunset", slug: "September30Sunset" },
  { file: "TONInvestorStructure", slug: "TONInvestorStructure" },
  { file: "TelegramMiniApps", slug: "TelegramMiniApps" },
  { file: "TikTokMiniGames", slug: "TikTokMiniGames" },
  { file: "UAGrowthStrategy", slug: "UAGrowthStrategy" },
  { file: "UnityWebGLBuildSystem", slug: "UnityWebGLBuildSystem" },
  { file: "UnityWebGLDeploy", slug: "UnityWebGLDeploy" },
  { file: "Web3PlayToEarn", slug: "Web3PlayToEarn" },
  { file: "WebGLCertificationStandard", slug: "WebGLCertificationStandard" },
  { file: "YouTubePlayables", slug: "YouTubePlayables" },

  // KEBAB-CASE BRIDGES (V5 INTERNAL LINKING)
  { file: "September30Sunset", slug: "september-30-sunset" },
  { file: "APIDeprecationTracker", slug: "api-deprecation-tracker" },
  { file: "PIIPrivacyCompliance", slug: "pii-privacy-compliance" },
  { file: "UnityWebGLDeploy", slug: "unity-webgl-deploy-hosting" },
  { file: "BeginnerDeployment", slug: "beginner-deployment-guide" },
  { file: "CICDWebGL", slug: "cicd-webgl-pipelines" },
  { file: "UnityWebGLBuildSystem", slug: "unity-webgl-build-system" },
  { file: "BuildErrorPatternTracking", slug: "build-error-pattern-tracking" },
  { file: "WebGLCertificationStandard", slug: "webgl-certification-standard" },
  { file: "BuildTroubleshooting", slug: "unity-webgl-build-troubleshooting" },
  { file: "MetaSDKMigration", slug: "meta-sdk-v8-migration" },
  { file: "DiscordActivitiesAPISplit", slug: "discord-activities-api-split" },
  { file: "TikTokMiniGames", slug: "tiktok-mini-games" },
  { file: "TelegramMiniApps", slug: "telegram-mini-apps" },
  { file: "YouTubePlayables", slug: "youtube-playables" },
  { file: "LinkedInB2BGaming", slug: "linkedin-b2b-gaming" },
  { file: "EUDMAArticle7", slug: "eu-dma-article7" },
  { file: "PlatformAPIChangeAlerts", slug: "platform-api-change-alerts" },
  { file: "RegulatoryBulletins", slug: "regulatory-bulletins" },
  { file: "DeveloperForumSignals", slug: "developer-forum-signals" },
  { file: "HyperCasualMarket", slug: "hyper-casual-market" },
  { file: "Web3PlayToEarn", slug: "web3-play-to-earn" },
  { file: "AIInGameDev", slug: "ai-in-game-dev" },
  { file: "CloudStreamingBrowserTech", slug: "cloud-streaming-browser-tech" },
  { file: "AdNetworkIntegrations", slug: "ad-network-integrations" },
  { file: "IAPStarsTON", slug: "iap-stars-ton-payments" },
  { file: "UAGrowthStrategy", slug: "ua-growth-strategy" },
  { file: "GameValuationsMA", slug: "game-valuations-ma" },
  { file: "GDPRCCPACompliance", slug: "gdpr-ccpa-compliance" },
  { file: "ContentModerationAgeRatings", slug: "content-moderation-age-ratings" },
  { file: "IPLicensingWebGL", slug: "ip-licensing-webgl" },
  { file: "GodotAlternativeEngines", slug: "godot-alternative-engines" },
  { file: "SDKIntegrationGuides", slug: "sdk-integration-guides" },
  { file: "PerformanceProfiling", slug: "performance-profiling" },
];
